server:
  port: 1200

spring:
  application:
    name: config-server
  profiles:
      active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ithuangbin/config-repo
          default-label: ${spring.profiles.active}   #解决监控down
          search-paths: /**
          username: 413896516@qq.com
          password: huang1990922

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:1001/eureka/

# 关闭安全管理
management:
  security:
    enabled: false
endpoints:
  health:
    sensitive: false