server:
  port: 1002
pring:
  application:
    name: admin-monitor
  profiles:
      active: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:1001/eureka/
  instance:
    prefer-ip-address: true
    health-check-url-path:

security:
  basic:
    enabled: false
spring:
  application:
    name: feign-consumer
  profiles:
    active: dev
  cloud:
    config:
      fail-fast: true
      discovery:
        service-id: config-server
        enabled: true
      profile: ${spring.profiles.active}
      label: master
      uri: http://localhost:1200

management:
  security:
    enabled: false
